name: Build Windows EXE (whisper_mini)

on:
  workflow_dispatch:  # run manually from GitHub Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # adjust if your app needs a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build whisper_mini EXE
        run: |
          pyinstaller --onefile --windowed whisper_mini.py
          # Optional: add custom icon if you have one (e.g., app.ico)
          # pyinstaller --onefile --windowed --icon=app.ico whisper_mini.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper_mini-exe
          path: dist/*.exe
