name: Build Whisper Mini EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile whisper_mini.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper_mini_exe
          path: dist/whisper_mini.exe
